language: php

php:
  - 7.0
  - 7.1

env:
  - DB=mysql

# For easy compatibility with docker env.
addons:
  hosts:
    - mysql

before_script:
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - travis_retry composer install --prefer-dist --no-interaction

  - mysql -e 'CREATE DATABASE test;'
